export const MINI_NUMBERS: Record<string, 'red' | 'black' | 'green'> = {
  '0': 'green',
  '1': 'red',
  '3': 'red',
  '5': 'red',
  '7': 'red',
  '9': 'red',
  '12': 'red',
  '14': 'red',
  '16': 'red',
  '18': 'red',
  '2': 'black',
  '4': 'black',
  '6': 'black',
  '8': 'black',
  '10': 'black',
  '11': 'black',
  '13': 'black',
  '15': 'black',
  '17': 'black'
}
